# Mathematical Computing with Python NumPy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Limitations-of-Lists" data-toc-modified-id="Limitations-of-Lists-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Limitations of Lists</a></span></li><li><span><a href="#NumPy" data-toc-modified-id="NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>NumPy</a></span></li><li><span><a href="#Purpose-of-ndarray" data-toc-modified-id="Purpose-of-ndarray-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Purpose of ndarray</a></span></li><li><span><a href="#Types-of-Arrays" data-toc-modified-id="Types-of-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Types of Arrays</a></span></li><li><span><a href="#Classes-and-Attributes-of-ndarray:-.ndim" data-toc-modified-id="Classes-and-Attributes-of-ndarray:-.ndim-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Classes and Attributes of ndarray: .ndim</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Accessing-Array-Elements:-Indexing" data-toc-modified-id="Accessing-Array-Elements:-Indexing-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Accessing Array Elements: Indexing</a></span></li><li><span><a href="#Accessing-Array-Elements:-Slicing" data-toc-modified-id="Accessing-Array-Elements:-Slicing-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Accessing Array Elements: Slicing</a></span></li><li><span><a href="#Accessing-Array-Elements:-Iteration" data-toc-modified-id="Accessing-Array-Elements:-Iteration-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Accessing Array Elements: Iteration</a></span></li><li><span><a href="#Indexing-with-Boolean-Arrays" data-toc-modified-id="Indexing-with-Boolean-Arrays-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Indexing with Boolean Arrays</a></span></li><li><span><a href="#Copy-and-Views" data-toc-modified-id="Copy-and-Views-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Copy and Views</a></span></li><li><span><a href="#Universal-Functions-(ufunc)" data-toc-modified-id="Universal-Functions-(ufunc)-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Universal Functions (ufunc)</a></span></li><li><span><a href="#Shape-Manipulation" data-toc-modified-id="Shape-Manipulation-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Shape Manipulation</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Broadcasting</a></span></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Linear Algebra</a></span></li></ul></div>

__Mathematical Computing with Python (NumPy)__

List is a collection of values of multiple types (heterogeneous)

In [1]:
List = [.30,'a',1,"FIFA"]
List

[0.3, 'a', 1, 'FIFA']

#### Limitations of Lists
we can change individual values in a list, but you cannot apply a mathematical operation over the entire list. This is where Numpy comes in handy.

In [2]:
Distance = [10, 15, 17]
Time= [.40,.37,.15]
Speed = Distance/Time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

#### NumPy
___Numerical Python (NumPy) supports multidimensional arrays over which you can easily apply mathematical operations.___

___Note:compare the exectution time___

In [3]:
import numpy as np
Distance = [10, 15, 17]
Time= [.40,.37,.15]
np_distance = np.array(Distance)
np_time= np.array(Time)
Speed = (np_distance/np_time)
#round(decimal points)
Speed.round(3)

array([ 25.   ,  40.541, 113.333])

Numpy arrays are collection of Values of singel type (Homogeneous) and Multidimentional, supports Mathematical function of ndarray, fast and efficient

#### Purpose of ndarray
The ndarray in Python is used as the primary container to exchange data between algorithms.

#### Types of Arrays
Arrays can be 
1. one-dimensional, 
2. two-dimensional, 
3. three-dimensional, or 
4. multi-dimensional.

#### Classes and Attributes of ndarray: .ndim
Numpy’s array class is ndarray, also referred to as numpy.ndarray. 

The attributes of ndarray are 
1. ndarray.ndim, 
2. ndarray.shape, 
3. ndarray.size, 
4. ndarray.dtype

In [4]:
print(Speed.ndim)
print(Speed.dtype)
print(Speed.size)
print(Speed.shape)
print(type(Speed))  # 1D array

x = np.array([[2,3,1],[0,5,9]])
print('\n',x.ndim)
print(x.dtype)
print(x.size)
print(x.shape)
print(type(x))  # 1D array

z=x
z

1
float64
3
(3,)
<class 'numpy.ndarray'>

 2
int32
6
(2, 3)
<class 'numpy.ndarray'>


array([[2, 3, 1],
       [0, 5, 9]])

#### Operations 
__Basic Operations__

NumPy uses the indices of the elements in each array to carry out basic operations. 

1. Mathematical Operations: +, -, *, /, **
2. Logical Operations: 
* And ==> &
* Or ==> |
* Not ==> ~
3. Comparison Operations: >, >=, <, <=, ==, !=.

In [5]:
#Example:
#Dataset of four cyclists during two trials, vector addition of the arrays gives the required output.

First_trial_cyclist = [10,15,17,26] #kms
Second_trial_cylcist = [12,11,21,24] #kms
np_First_trial_cyclist = np.array(First_trial_cyclist)
np_Second_trial_cyclist = np.array(Second_trial_cylcist)
np_First_trial_cyclist +  np_Second_trial_cyclist

array([22, 26, 38, 50])

#### Accessing Array Elements: Indexing
we can access an entire row of an array by referencing its axis index.

In [6]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
first_trial = cyclist_trials[0]
print(first_trial)

first_cyclist_first_trial = cyclist_trials[0][0]
print(first_cyclist_first_trial)

# ':' used to select all rows, here all rows but 0th column
first_cyclist_all_trial = cyclist_trials[:,0]
print(first_cyclist_all_trial)

[10 15 17 26]
10
[10 12]


In [7]:
Second_trial = cyclist_trials[1]
Second_trial

array([12, 11, 21, 24])

#### Accessing Array Elements: Slicing
Use the slicing method to access a range of values within an array.

In [8]:
#shape of the nparray (2 roes X 4 Columns)
cyclist_trials.shape

(2, 4)

In [9]:
#slice all row, but '1' to (3-1) columns, i.e, column 1 & 2
cyclist_trials[:,1:3]

array([[15, 17],
       [11, 21]])

#### Accessing Array Elements: Iteration
Use the iteration method to go through each data element present in the dataset.

In [10]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])
two_cyclist_trial_data = cyclist_trials[:,1:3]
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [11]:
#Iterate with for loop through entire dataset
for iterate_cyclist_trial_data in cyclist_trials:
    print(iterate_cyclist_trial_data)


[10 15 17 26]
[12 11 21 24]


In [12]:
#Iterate with for loop through the two cyclist datasets
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print(iterate_two_cyclist_trial_data)

[15 17]
[11 21]


#### Indexing with Boolean Arrays
Boolean arrays are useful when you need to select a dataset according to set criteria
* True
* False

In [37]:
#Example
#dataset contains test scores of two students. You can use a Boolean array to choose only the scores that are above a given value.

test_scores=np.array([[83,71,57,63],[54,63,81,45]])
#Setting the passing score
passing_score = test_scores > 60
#Shows data elements which fit the criteria (Boolean array: passing_score)
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [14]:
#Send passing score as an argument to test scores object
test_scores[passing_score]

array([83, 71, 63, 63, 81])

#### Copy and Views
When working with arrays, data is copied into new arrays only in some cases. Following are the three possible scenarios:

1. Simple Assignments
2. View/Shallow Copy
3. Deep Copy

__Simple Assignment__

In this method, a variable is directly assigned the value of another variable. No new copy is made.

In [38]:
#Original dataset
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','Staten Island','Queens'])
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [39]:
#Assigned dataset
Boroughs_in_NYC = NYC_Borough
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [40]:
#Shows both objects are the same
Boroughs_in_NYC in NYC_Borough

True

In [41]:
#Shows copyand original object are same 
Boroughs_in_NYC is NYC_Borough

True

In [42]:
#Shows copyobject data is not owned by the original dataset
Boroughs_in_NYC.base is NYC_Borough

False

__View/Shallow Copy__

A view, also referred to as a shallow copy, creates a new array object.
A shallow copy creates a new object which stores the reference of the original elements


In [43]:
#Original Dataset
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [44]:
Views_of_Borough_in_NYC = Boroughs_in_NYC.view()
Views_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [45]:
#Shows copyand original object are different 
Views_of_Borough_in_NYC is Boroughs_in_NYC

False

In [46]:
#Shows copyobject data is owned by the original dataset
Views_of_Borough_in_NYC.base is Boroughs_in_NYC

True

In [22]:
#Change value in view object
Views_of_Borough_in_NYC[4] = 'Central Park'
Views_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

In [23]:
#the change is reflected in Boroughs_in_NYC Original dataset, This is because, both lists share the same reference.
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

__Deep Copy__

.copy() in numpy is also called deep copy because it entirely copies the original dataset. Any change in the copy will not affect the original dataset.
A deep copy creates a new object and recursively adds the copies of nested objects present in the original elements.

In [47]:
copy_of_NYC_Borough = NYC_Borough.copy()

In [48]:
#Shows copyand original object are different 
copy_of_NYC_Borough is NYC_Borough

False

In [49]:
#Shows copyobject data is not owned by the original dataset
copy_of_NYC_Borough.base is NYC_Borough

False

In [51]:
#Change value in copy
copy_of_NYC_Borough[4] = 'Central Park'

In [52]:
#Original Dataset retained
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Queens'],
      dtype='<U13')

In [53]:
#Copyobject changed
copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'Staten Island', 'Central Park'],
      dtype='<U13')

#### Universal Functions (ufunc)

NumPy provides useful mathematical functions called Universal Functions. These functions operate element-wise on an array, producing another array as output. Some of these functions are:
1. __sqrtfunction__ provides the square root of every element in the array
2. __cosfunction__ from Trigonometric functions gives cosine values for all elements in the array. 
3. __sinfunction__ from Trigonometric functions gives sine values for all elements in the array.
4. __floorfunction__ returns the largest integer value of every element in the array.
5. __expfunction__ performs exponentiation on each element.

In [67]:
import numpy
print(numpy.__version__)
# see all the ufunc in NumPy v1.19 Manual

1.19.2


__sqrtfunction__

In [54]:
#Numbers for which square root will be calculated
np_sqrt=np.sqrt([2,4,9,16])

In [61]:
#Square root values
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

__Trigonometric functions__

In [62]:
#importing pi from numpy
from numpy import pi
#cos (0)
np.cos(0)

1.0

In [59]:
#sin (pi/2)
np.sin(pi/2)

1.0

In [60]:
#cos (pi)
np.cos(pi)

-1.0

__Floor function__

In [63]:
#Return the floor of the input element wise
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

__Exponential function__

In [68]:
#Exponential functions for complex mathematical calculations
np.exp([0,1,5])

#Eulers constant 'e'
#e^0 = 1
#e or e^1 = 2.71828183...

array([  1.        ,   2.71828183, 148.4131591 ])

In [80]:
np.pi

3.141592653589793

#### Shape Manipulation

You can use certain functions to manipulate the shape of an array.The shape of an array can be changed according to the requirement using the NumPy library functions.

Array shape manipulation methods  ==> Data Wrangling

Some common methods for manipulating shapes are:
1. Flatten (.ravel)
2. Reshape (.reshape(n,m))
3. Resize (.resize(n,m))
4. Split (.hsplit(nparray,no.times to split))
5. Stack (.hstack((x,y)))

In [83]:
new_cyclist_trails = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

__Flatten__

__.ravel()__

In [85]:
#Flattens the dataset
#Falttens nested np.array to single np.array
new_cyclist_trails.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [101]:
new_cyclist_trails

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

__Reshape__

__.reshape(rows,columns)__

we can see reshape created a reshaped new instance of the data while the original new_cyclist_trails stayed unchanged

In [100]:
new_cyclist_trails

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [87]:
#Changes or reshapes the dataset to 3 rows and 4 columns
new_cyclist_trails.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [106]:
#original data unchanged
new_cyclist_trails

array([[10, 15],
       [17, 26],
       [13, 19],
       [12, 11],
       [21, 24],
       [14, 23]])

__Resize__

__.resize(rows,columns)__

resize wii not create a new instance, the changes were applied to the original array new_cyclist_trails directly 

resize is called in-place operation

In [105]:
#Resizes again to 6 rows and 2 columns
new_cyclist_trails.resize(6,2)

In [104]:
new_cyclist_trails

array([[10, 15],
       [17, 26],
       [13, 19],
       [12, 11],
       [21, 24],
       [14, 23]])

In [99]:
new_cyclist_trails.resize(4,4)
new_cyclist_trails

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

__Split__

__.hsplit(nparray,no.times to split)__

In [90]:
#Splits the array into two
np.hsplit(new_cyclist_trails,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 23]])]

__Stack__

__.hstack((nparray1,nparray2))__

In [95]:
#Stacks the arrays together
new_cyclist_1 = np.array([10, 15, 17, 26, 13, 19]) 
new_cyclist_2 = np.array([12, 11, 21, 24, 14, 23])
np.hstack((new_cyclist_1,new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

#### Broadcasting

NumPy uses broadcasting to carry out arithmetic operations between arrays of different shapes. In this method, NumPy automatically broadcasts the smaller array over the larger array.

In [108]:
import numpy as np
#Two arrays of same shape
array_a = np.array([2,3,5,8])
array_b = np.array([0.3,0.3,.3,.3])

#Elementwise multiplication 
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

__Multiplying 1D array with a scalar__

If the shape doesn’t match with array_a, numpy doesn’t have to create copies of scalar value. Instead, broadcast scalar value over the entire array to find the product.

In [110]:
Scalar_c = 0.3
array_a * Scalar_c

array([0.6, 0.9, 1.5, 2.4])

__Broadcasting: Constraints__

Though broadcasting can help carry out mathematical operations between different-shaped arrays, they are subject to certain constraints as listed below:

1. When NumPy operates on two arrays, it compares their shapes element-wise. It finds these shapes compatible only if:
    * Their dimensions are the same or
    * One of them has a dimension of size 1.
2. If these conditions are not met, a ValueErroris thrown, indicating that the arrays have incompatible shapes.

In [111]:
array_a = np.array([2,3,5,8])
array_b = np.array([0.3,0.3,.3,.3])
#multiplying arrays of same shape
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [112]:
#Creating an array of different shape
array_d = np.array([4,3])
#Multiplying array of different shape
array_a * array_d

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

__Broadcasting: Example__

Let’s look at an example to see how broadcasting works to calculate the number of working hours of a worker per day in a certain week.

In [115]:
#week one earnings
np_week_one = np.array([105,135,195,120,165])
#week two earnings
np_week_two = np.array([123,156,230,200,147])

#Elementwise additon operation
total_earnings = np_week_one + np_week_two
total_earnings

array([228, 291, 425, 320, 312])

In [116]:
#calculate week one hours
# hourly wage = 15
np_week_one_hrs = np_week_one / 15

#Number of working hours per day in week one
np_week_one_hrs

array([ 7.,  9., 13.,  8., 11.])

#### Linear Algebra

NumPy can carry out linear algebraic functions as well.

__Transpose__

The transpose() function can help you interchange rows as columns, and vice-versa.

In [118]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

In [125]:
test_scores.shape

(2, 4)

In [120]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [122]:
test_scores

array([[83, 71, 57, 63],
       [54, 68, 81, 45]])

__Inverse and Trace Functions__

Using NumPy, you can also find the inverse of an array and add its diagonal data elements.

__Inverse Function__

__np.linalg.inv()__

__Can be applied onlyon a square matrix__

In [127]:
inverse_array = np.array([[10,20],[15,25]])
inverse_array

array([[10, 20],
       [15, 25]])

In [129]:
#Inverse of the given array
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

__Trace Function__

__np.trace()__

__Sum of diagonal elements, in this case a00 and b11__ 

In [130]:
trace_array = np.array([[10,20],[22,31]])
np.trace(trace_array)

41