# Scientific computing with Python (Scipy)

#### Scipy

SciPy has built-in packages that help in handling the scientific domains.

some of the domains are:
1. Space Science
2. Image Science
3. Statistics
3. Mathematical equations
4. Platform Integration
5. Signal processing
6. Optimization

#### SciPy and Its Characteristics

1. Built-in mathematical libraries and functions
2. High-level commands for data manipulation and visualization
3. Efficient and fast data processing
4. Integrates well with multiple systems and environments
5. Large collection of sub-packages for different scientific domains
6. Simplifies scientific application development

#### SciPy Packages

Some widely used packages are:
* IO
* Optimize
* Weave Packages
* Statistics
* Integration 
* Linear Algebra

#### Introduction of SciPy Sub-Package

SciPy has multiple sub-packages which handle different scientific domains.
* __cluster__: Clustering Algorithm
* __constants__: Physical and mathematical constant
* __fftpack__: Fast Fourier Transform routines
* __integrate__: Integration and ordinary differential equation solver
* __Spatial__: Spatial data structures and algorithms
* __interpolate__: Interpolation and smoothing splines
* __IO__: Input and Output
* __linalg__: Linear algebra
* __ndimage__: N-dimensional image processing
* __odr__: Orthogonal distance regression
* __optimize__: Optimization and root-finding routines
* __signal__: Signal processing
* __sparse__: Sparse matrices and associated routines
* __weave__: C/C++ integration
* __stats__: Statistical distributions and functions
* __special__: Special functions


#### SciPy Sub-Package: Integration

SciPy provides integration techniques that solve mathematical sequences and series,  or perform function approximation.

__General integration (quad)__
* integrate.quad(f, a, b)

__General multiple integration (dblquad, tplquad, nquad)__
* integrate.dblquad()
* integrate.tplquad()
* integrate.nquad()

The limits of all inner integrals need to be defined as functions.

This example shows you how to perform quad integration. 

In [1]:
#Import quad from integrate sub-package
from scipy.integrate import quad

#Define function for integration of x
def integrateFunction(x):
    return x

#Perform quad integration for function of x for limit 0 to 1 
quad(integrateFunction, 0, 1)

(0.5, 5.551115123125783e-15)

In [2]:
#Define function for ax + b
def integratedFn(x,a,b):
    return x*a+b

#Declare value of a and b
a=3
b=2

#Perform quad integration and pass functions and arguments
quad(integratedFn, 0, 1, args=(a, b))

(3.5, 3.885780586188048e-14)

This example shows you how to perform multiple integration. 

In [3]:
#import integrate package sub-package
import scipy.integrate as integrate

#Define function for x+y
def f(x,y):
    return x + y

#Perform multiple integration using the lambda built-in function
integrate.dblquad(f,0,1,lambda x:0, lambda x:2)

(3.0, 4.436070580899685e-14)

__Lamda Constructor__

The below expression is composed of:

* __The keyword__: lambda
* __A bound variable__: x
* __A body__: x

__lambda x: x__

A lambda function is an expression, it can be named. Therefore we could write the code as follows:

In [4]:
add_one = lambda x: x + 1
add_one(2)

3

we can apply the function above to an argument by surrounding the function and its argument with parentheses:

In [5]:
#x+1 ==> 9+1 = 10
(lambda x: x + 1)(9)

10

The above lambda function is equivalent to writing this:

In [6]:
def add_one(x):
    return x + 1
add_one(3)

4

#### SciPy Sub-Package: Optimization

Optimization is a process to improve performance of a system mathematically by fine-tuning the process parameters. 

SciPy provides several optimization algorithms, such as bfgs, Nelder-Mead simplex, Newton Conjugate Gradient, COBYLA, or SLSQP.

__Minimization functions__

optimize.minimize(f, x0, method=‘BFGS’), 
where x0 is the lower limit in a given range

__Root finding, Curve fitting__

root(f, x0, method=’hybr’)

optimize.curve_fit(f, xdata, ydata)

In [7]:
#Import numpy and optimize from SciPy
import numpy as np
from scipy import optimize

#Define function for x
def f(x):
    #Define function for X^2 + 5 sin x
    return x**2 + 5*np.sin(x)

#Perform optimize minimize function using bfgs method and options
MinimumValue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [8]:
#Perform optimize minimize function using bfgs method and without options
MinimumValuewithoutput = optimize.minimize(f,x0=2,method='bfgs')
MinimumValuewithoutput

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [9]:
#Import numpy and optimize from SciPy
import numpy as np
from scipy.optimize import root

#Define function for X + 3.5 Cos x
def rootfunc(x):
    return x+3.5*np.cos(x)

#Pass x value in argument for root
rootValue = root(rootfunc,0.3)
#Function value and array values
rootValue

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

#### SciPy Sub-Package: Linear Algebra

SciPy provides rapid linear algebra capabilities and contains advanced algebraic functions.

##### inverse of matrix

This function is used to compute the inverse of the given matrix. Let’s look at the inverse matrix operation.

In [10]:
#Import linalg and Define a numpy matrix  or array
import numpy as np
from scipy import linalg
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [11]:
#view type
type(matrix)

numpy.ndarray

In [12]:
#Use inv function to inverse the matrix
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

##### Finding Determinant

With this function you can compute the value of the determinant for the given matrix.

In [13]:
#Import linalg and Define a numpy matrix  or array
import numpy as np
from scipy import linalg
matrix = np.array([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [14]:
linalg.det(matrix)

-6.999999999999999

##### Solve Linear systems (linalg.solve())

__Linear equation__

* 2x + 3 y + z = 21
* -x + 5y + 4z = 93
* x + 2y + 9z = 6

In [15]:
#Import linalg and Define a numpy matrix  or array
import numpy as np
from scipy import linalg

numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])
numArrayValue = np.array([21,9,6])

#Use solve method
linalg.solve(numArray, numArrayValue)

array([ 4.95,  4.35, -1.95])

__Calculate Eigenvalues and Eigenvectors__

__Problem Statement:__ Demonstrate how to calculate eigenvalues and eigenvectors

In [16]:
#import the required Libraries
import numpy as np
from scipy import linalg

#test data matrix (rating on scale of 10) (Sqaure matrix)
test_rating_data = np.array([[5,8],[7,9]])
eigenvalues, eigenvectors = linalg.eig(test_rating_data)
print(eigenvalues)
print('\n',eigenvectors)
print('\n',linalg.eig(test_rating_data))

[-0.74596669+0.j 14.74596669+0.j]

 [[-0.81220939 -0.63447346]
 [ 0.58336601 -0.77294465]]

 (array([-0.74596669+0.j, 14.74596669+0.j]), array([[-0.81220939, -0.63447346],
       [ 0.58336601, -0.77294465]]))


In [17]:
#print Eigenvalues (1st and 2nd Eigenvalues)
first_eigenvalues, second_eigenvalues = eigenvalues
print (first_eigenvalues, second_eigenvalues)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [18]:
#print First Eigenvector using slicing technoque by apllying :0 to print first eigenvector
print (eigenvectors[:,0])

[-0.81220939  0.58336601]


In [19]:
#print Second Eigenvector using slicing technoque by apllying :1 to print Second eigenvector
print (eigenvectors[:,1])

[-0.63447346 -0.77294465]


##### Single Value Decomposition (SVD)

In [20]:
#Import linalg
import numpy as np
from scipy import linalg

#Define matrix
numSVDarray = np.array([[3,5,1],[9,5,7]])

#Find shape of ndarray which is  2X3 matrix 
numSVDarray.shape

(2, 3)

In [21]:
#use SVD function
linalg.svd(numSVDarray)

# 1. U (Unitary matrix)
# 2. Sigma or square root of eigenvalues
# 3. VH is values collected into unitary matrix

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

#### SciPy Sub-Package: Statistics

SciPy provides a very rich set of statistical functions which are:

* This package contains distributions for which random variables are generated. 
* These packages enable the addition of new routines and distributions.  It also offers convenience methods such as pdf(), cdf()
* Following are the statistical functions for a set of data
    * linear regression: linregress()
    * describing data: describe(), normaltest()
    
__CDF or Cumulative Distribution Function__ provides the cumulative probability associated with a function.

__Derivative of cdf__

* __F(x) = P(X≤x)__

__Probability Density Function or PDF__ of a continuous random variable is the derivative of its Cumulative Distribution Function, or CDF.

__Derivative of pdf__

* __F(x) = dF(x) / dx__

Shown here are functions used to perform Normal Distribution:

__loc and scale are used to adjust the location and scale of the data distribution.__

In [22]:
#Import norm for normal distribution 
from scipy.stats import norm

#rvs for random variables
norm.rvs(loc=0,scale=1,size=10)

array([ 0.83316749, -0.05919067, -0.06751606,  0.5893463 , -0.05737175,
        0.40455729, -0.70556572,  1.12323875, -1.90470273,  0.14285252])

In [23]:
#cdf for Cumulative Distribution Function
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [24]:
#pdf for Probability Density Function for random distribution
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18

#### SciPy Sub-Package: Weave

The weave package provides ways to modify and extend any supported extension libraries.

__Features of Weave Package:__
* Includes C/C++ code within Python code
* Speed ups of 1.5x to 30x compared to algorithms written in pure Python

__Two main functions of weave:__
* inline() compiles and executes C/C++ code on the fly
* blitz() compiles NumPy Python expressions for fast execution

#### SciPy Sub-Package: IO

The IO package provides a set of functions to deal with several kinds of file formats.

It offers a set of functions to deal with file formats that include:
* MatLab file
* IDL files
* Matrix market files
* Wav sound files
* Arff files
* Netcdf files

Package provides additional files and its corresponding methods such as:
* Numpy.loadtxt()/Numpy.savetxt()
* Numpy.genfromtxt()/Numpy.recfromcsv()
* Numpy.save()/Numpy.load()